#
# Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

obj-${CONFIG_MOXA_CONSOLE} += moxa_console.o 
obj-${CONFIG_MOXA_LIB} += moxa_lib.o
obj-${CONFIG_MOXA_LED} += led.o
obj-${CONFIG_MOXA_RTC} += rtc.o
obj-${CONFIG_MOXA_ETH} += ethernet.o
obj-${CONFIG_MOXA_SD} += sd.o
obj-${CONFIG_MOXA_MEM} += moxa_mem.o
obj-${CONFIG_MOXA_SATA} += sata.o
obj-${CONFIG_MOXA_USB} += usbh.o
obj-${CONFIG_MOXA_UART} += uart.o
obj-${CONFIG_MOXA_DIO} += dio.o
obj-y += wdt_diag.o ds1374_wdt.o
obj-y += sys_info.o
obj-${CONFIG_MOXA_WDT} += ds1374_wdt.o
obj-${CONFIG_MOXA_ADM6318} += adm6318_wdt.o
obj-${CONFIG_MOXA_USB_SIGNAL_INIT} += usb_signal_init.o
obj-${CONFIG_MOXA_SIERRA_GPS} += sierra_gps.o
obj-${CONFIG_MOXA_CELLULAR} += cellular.o
obj-${CONFIG_MOXA_OLED} += oled.o
obj-${CONFIG_MOXA_GPIO} += gpio.o
obj-${CONFIG_MOXA_TPM} += tpm_mp.o
obj-${CONFIG_MOXA_TPM2} += tpm2_mp.o
obj-${CONFIG_MOXA_CPU} += cpu_mp.o
obj-${CONFIG_MOXA_BOOT} += moxa_boot.o
obj-${CONFIG_MOXA_TEST} += test.o
obj-${CONFIG_MOXA_UPGRADE} += moxa_upgrade.o

